# ANN Model

![image.png](mlp-diagram.jpg)

In [1]:
from keras.models import Sequential
from keras.layers import  Input , Dense

In [2]:
model = Sequential()

# Add input layer 
model.add(Input(shape=(4,)))

# Add first hidden layer (Dense layer)
model.add(Dense(3, activation='relu'))

# Add output layer (for binary classification, activation='sigmoid')
model.add(Dense(1, activation='sigmoid'))

In [3]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 3)                   │              15 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │               4 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 19 (76.00 B)

 Trainable params: 19 (76.00 B)

 Non-trainable params: 0 (0.00 B)

# RNN (Recurrent Neural Network) Applications:

1. [Gmail](https://mail.google.com/)
2. [Sentiment analysis](https://text2data.com/Demo)
3. [Google Translate](https://www.google.com/search?q=google+translate&oq=google+tr&gs_lcrp=EgZjaHJvbWUqDQgAEAAYgwEYsQMYgAQyDQgAEAAYgwEYsQMYgAQyDwgBEEUYORiDARixAxiABDIHCAIQABiABDINCAMQABiDARixAxiABDIGCAQQRRg8MgYIBRBFGEEyBggGEEUYPDIGCAcQRRhB0gEIMjAxNGowajSoAgCwAgE&sourceid=chrome&ie=UTF-8)
4. Time-series forecasting ( Stock market price prediction, Weather forecast)
5. Speech Recognition

# Recurrent Neural Network - RNN

![img.jpg](rnn-2.drawio.png)

# RNN Architecture

![image.png](RNN-unrolled.png) 

# RNN Model

In [4]:
from keras.models import Sequential
from keras.layers import Input,SimpleRNN, Dense

In [5]:
# Define model
model = Sequential()

In [6]:
# input_shape = (timesteps, features)

model.add(Input(shape=(10,5)))  # input shape of (10 timesteps, 5 feature)

model.add(SimpleRNN(4, activation='relu')) # 3 units in RNN layer

# Add a Dense layer for output
model.add(Dense(1, activation='sigmoid'))  # Output layer with one unit

In [7]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ simple_rnn (SimpleRNN)               │ (None, 4)                   │              40 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │               5 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 45 (180.00 B)

 Trainable params: 45 (180.00 B)

 Non-trainable params: 0 (0.00 B)

# Next Word Predictor Using LSTM

In [8]:
resume = """
Saurav Kapadiya
ThinkBiz Technology Pvt Ltd: Junior Python Developer May 2024 - present
 Developed and deployed live products utilizing OCR technology and large language models (LLMs) such as
GPT.
 Improved data extraction accuracy and natural language processing capabilities using advanced AI tech-
niques.
 Collaborated with cross-functional teams to integrate AI solutions seamlessly into existing systems.

Institute for Plasma Research: Project intern Jan 2024 - May 2024
 Project Title: Optimized LSTM-based Deep Learning Model for Real-Time Plasma Disruption Event Pre-
diction
 Developed and optimized an LSTM time-series model for predicting plasma disruption events in tokamak
fusion reactors.
 Achieved significant improvement in model accuracy through optimization techniques, enabling real-time
deployment on a dedicated server for early disruption warnings

AI Mock Interviewer
 Developed an AI-driven speech-based interviewer platform designed to streamline the interview process by
leveraging speech recognition and synthesis technologies.
 Employed advanced NLP models (e.g., Gemini) to parse job descriptions and CVs, generating customized
and contextually relevant interview questions.
 Enabled continuous listening and speaking capabilities for dynamic and engaging interview sessions.
Automatic CAPTCHA Recognition
 Successfully built and trained an OCR model using TensorFlow & Keras.
 Implemented a CNN architecture with multiple Convolutional and Pooling layers to extract features from
CAPTCHA images.
 Project focused on breaking down captchas into individual characters for improved recognition.

Education
Nov 2020 - present B.Tech (Information and Communication Technology)
at Dhirubhai Ambani Institute of Information
and Communication Technology (DA-IICT)

June 2019 - May 2020 Class 12th GHSEB 
June 2017 - May 2018 Class 10th GSEB

Python Machine learning, Deep learning, OpenCV, Computer Vision, Flask, Prompt Engineer-
ing, LLMs
C/C++ Data structures and Algorithms, Object-Oriented Programming
"""

In [9]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [10]:
tokenizer = Tokenizer()

In [11]:
tokenizer.fit_on_texts([resume])

In [12]:
tokenizer.word_index

{'and': 1,
 'for': 2,
 'technology': 3,
 'may': 4,
 'ai': 5,
 'to': 6,
 'model': 7,
 '2024': 8,
 'developed': 9,
 'plasma': 10,
 'project': 11,
 'learning': 12,
 'time': 13,
 'disruption': 14,
 'an': 15,
 'interview': 16,
 'recognition': 17,
 'python': 18,
 'present': 19,
 'ocr': 20,
 'language': 21,
 'models': 22,
 'llms': 23,
 'improved': 24,
 'data': 25,
 'accuracy': 26,
 'capabilities': 27,
 'using': 28,
 'advanced': 29,
 'tech': 30,
 'with': 31,
 'into': 32,
 'institute': 33,
 'optimized': 34,
 'lstm': 35,
 'based': 36,
 'deep': 37,
 'real': 38,
 'in': 39,
 'on': 40,
 'a': 41,
 'interviewer': 42,
 'speech': 43,
 'captcha': 44,
 '2020': 45,
 'information': 46,
 'communication': 47,
 'june': 48,
 'class': 49,
 'c': 50,
 'saurav': 51,
 'kapadiya': 52,
 'thinkbiz': 53,
 'pvt': 54,
 'ltd': 55,
 'junior': 56,
 'developer': 57,
 'deployed': 58,
 'live': 59,
 'products': 60,
 'utilizing': 61,
 'large': 62,
 'such': 63,
 'as': 64,
 'gpt': 65,
 'extraction': 66,
 'natural': 67,
 'processing

In [13]:
len(tokenizer.word_index)

187

In [14]:
input_sequences = []

for sentence in resume.split('\n'):
    print(tokenizer.texts_to_sequences([sentence])[0])
    tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]


    for i in range(1,len(tokenized_sentence)):
        input_sequences.append(tokenized_sentence[:i+1])

[]
[51, 52]
[53, 3, 54, 55, 56, 18, 57, 4, 8, 19]
[9, 1, 58, 59, 60, 61, 20, 3, 1, 62, 21, 22, 23, 63, 64]
[65]
[24, 25, 66, 26, 1, 67, 21, 68, 27, 28, 29, 5, 30]
[69]
[70, 31, 71, 72, 73, 6, 74, 5, 75, 76, 32, 77, 78]
[]
[33, 2, 10, 79, 11, 80, 81, 8, 4, 8]
[11, 82, 34, 35, 36, 37, 12, 7, 2, 38, 13, 10, 14, 83, 84]
[85]
[9, 1, 34, 15, 35, 13, 86, 7, 2, 87, 10, 14, 88, 39, 89]
[90, 91]
[92, 93, 94, 39, 7, 26, 95, 96, 97, 98, 38, 13]
[99, 40, 41, 100, 101, 2, 102, 14, 103]
[]
[5, 104, 42]
[9, 15, 5, 105, 43, 36, 42, 106, 107, 6, 108, 109, 16, 110, 111]
[112, 43, 17, 1, 113, 114]
[115, 29, 116, 22, 117, 118, 119, 6, 120, 121, 122, 1, 123, 124, 125]
[1, 126, 127, 16, 128]
[129, 130, 131, 1, 132, 27, 2, 133, 1, 134, 16, 135]
[136, 44, 17]
[137, 138, 1, 139, 15, 20, 7, 28, 140, 141]
[142, 41, 143, 144, 31, 145, 146, 1, 147, 148, 6, 149, 150, 151]
[44, 152]
[11, 153, 40, 154, 155, 156, 32, 157, 158, 2, 24, 17]
[]
[159]
[160, 45, 19, 161, 30, 46, 1, 47, 3]
[162, 163, 164, 33, 165, 46]
[1, 47,

In [15]:
input_sequences

[[51, 52],
 [53, 3],
 [53, 3, 54],
 [53, 3, 54, 55],
 [53, 3, 54, 55, 56],
 [53, 3, 54, 55, 56, 18],
 [53, 3, 54, 55, 56, 18, 57],
 [53, 3, 54, 55, 56, 18, 57, 4],
 [53, 3, 54, 55, 56, 18, 57, 4, 8],
 [53, 3, 54, 55, 56, 18, 57, 4, 8, 19],
 [9, 1],
 [9, 1, 58],
 [9, 1, 58, 59],
 [9, 1, 58, 59, 60],
 [9, 1, 58, 59, 60, 61],
 [9, 1, 58, 59, 60, 61, 20],
 [9, 1, 58, 59, 60, 61, 20, 3],
 [9, 1, 58, 59, 60, 61, 20, 3, 1],
 [9, 1, 58, 59, 60, 61, 20, 3, 1, 62],
 [9, 1, 58, 59, 60, 61, 20, 3, 1, 62, 21],
 [9, 1, 58, 59, 60, 61, 20, 3, 1, 62, 21, 22],
 [9, 1, 58, 59, 60, 61, 20, 3, 1, 62, 21, 22, 23],
 [9, 1, 58, 59, 60, 61, 20, 3, 1, 62, 21, 22, 23, 63],
 [9, 1, 58, 59, 60, 61, 20, 3, 1, 62, 21, 22, 23, 63, 64],
 [24, 25],
 [24, 25, 66],
 [24, 25, 66, 26],
 [24, 25, 66, 26, 1],
 [24, 25, 66, 26, 1, 67],
 [24, 25, 66, 26, 1, 67, 21],
 [24, 25, 66, 26, 1, 67, 21, 68],
 [24, 25, 66, 26, 1, 67, 21, 68, 27],
 [24, 25, 66, 26, 1, 67, 21, 68, 27, 28],
 [24, 25, 66, 26, 1, 67, 21, 68, 27, 28, 29],
 [

In [16]:
max_len = max([len(x) for x in input_sequences])

In [17]:
max_len

15

In [18]:
from keras.preprocessing.sequence import pad_sequences

padded_input_sequences = pad_sequences(input_sequences, maxlen=max_len, padding='pre')

print(padded_input_sequences)

[[  0   0   0 ...   0  51  52]
 [  0   0   0 ...   0  53   3]
 [  0   0   0 ...  53   3  54]
 ...
 [  0   0   0 ...   1 184 185]
 [  0   0   0 ... 184 185 186]
 [  0   0   0 ... 185 186 187]]


In [19]:
X = padded_input_sequences[:,:-1]
print(X)

[[  0   0   0 ...   0   0  51]
 [  0   0   0 ...   0   0  53]
 [  0   0   0 ...   0  53   3]
 ...
 [  0   0   0 ... 183   1 184]
 [  0   0   0 ...   1 184 185]
 [  0   0   0 ... 184 185 186]]


In [20]:
y = padded_input_sequences[:,-1]
print(y)

[ 52   3  54  55  56  18  57   4   8  19   1  58  59  60  61  20   3   1
  62  21  22  23  63  64  25  66  26   1  67  21  68  27  28  29   5  30
  31  71  72  73   6  74   5  75  76  32  77  78   2  10  79  11  80  81
   8   4   8  82  34  35  36  37  12   7   2  38  13  10  14  83  84   1
  34  15  35  13  86   7   2  87  10  14  88  39  89  91  93  94  39   7
  26  95  96  97  98  38  13  40  41 100 101   2 102  14 103 104  42  15
   5 105  43  36  42 106 107   6 108 109  16 110 111  43  17   1 113 114
  29 116  22 117 118 119   6 120 121 122   1 123 124 125 126 127  16 128
 130 131   1 132  27   2 133   1 134  16 135  44  17 138   1 139  15  20
   7  28 140 141  41 143 144  31 145 146   1 147 148   6 149 150 151 152
 153  40 154 155 156  32 157 158   2  24  17  45  19 161  30  46   1  47
   3 163 164  33 165  46  47   3 166 167 168   4  45  49 169 170 171   4
 172  49 173 174 175  12  37  12 176 177 178 179 180 181  23  50  25 183
   1 184 185 186 187]


In [21]:
X.shape

(239, 14)

In [22]:
y.shape

(239,)

In [23]:
num_classes = len(X)
num_classes

239

In [24]:
from keras.utils import to_categorical
y = to_categorical(y,num_classes=len(X))

In [25]:
y.shape

(239, 239)

In [26]:
from keras.models import Sequential
from keras.layers import Input, Embedding, LSTM, Dense, SimpleRNN

In [27]:
model = Sequential()
model.add(Input(shape=(14,)))
model.add(Embedding(input_dim=240,output_dim=100 ))
# model.add(SimpleRNN(200, activation='tanh'))
model.add(LSTM(200, activation='tanh'))
model.add(Dense(num_classes, activation='softmax'))

In [28]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [29]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ (None, 14, 100)             │          24,000 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm (LSTM)                          │ (None, 200)                 │         240,800 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 239)                 │          48,039 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 312,839 (1.19 MB)

 Trainable params: 312,839 (1.19 MB)

 Non-trainable params: 0 (0.00 B)

In [30]:
X

array([[  0,   0,   0, ...,   0,   0,  51],
       [  0,   0,   0, ...,   0,   0,  53],
       [  0,   0,   0, ...,   0,  53,   3],
       ...,
       [  0,   0,   0, ..., 183,   1, 184],
       [  0,   0,   0, ...,   1, 184, 185],
       [  0,   0,   0, ..., 184, 185, 186]])

In [31]:
model.fit(X,y, epochs=100)

Epoch 1/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - accuracy: 0.0199 - loss: 5.4763  
Epoch 2/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.0651 - loss: 5.4314
Epoch 3/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.0717 - loss: 5.1634
Epoch 4/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.0411 - loss: 4.9960
Epoch 5/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.0308 - loss: 4.9986
Epoch 6/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.0544 - loss: 4.9109
Epoch 7/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.0432 - loss: 4.8492
Epoch 8/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.0466 - loss: 4.8575
Epoch 9/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.0493 - loss: 4.7571
Epoch 10/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.0602 - loss: 4.6187
Epoch 11/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.0677 - loss: 4.5729
Epoch 12/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.0891 - 

In [32]:
import numpy as np

In [33]:
test = "Saurav"

In [34]:
token_text = tokenizer.texts_to_sequences([test])[0]
#padding
padded_token_text = pad_sequences([token_text], maxlen=14, padding='pre')
#predict
print(padded_token_text)

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0 51]]


In [35]:
predict = model.predict(padded_token_text)
predict

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 248ms/step


array([[9.89648811e-07, 4.20360098e-04, 1.49908680e-02, 4.37556719e-03,
        2.36750304e-04, 7.40033155e-03, 3.44822661e-06, 2.60779052e-04,
        6.09029630e-05, 1.19850574e-06, 2.09794077e-03, 6.59279103e-05,
        1.95323024e-04, 3.71080096e-04, 4.97024339e-05, 5.56121860e-03,
        4.79056034e-05, 4.39695228e-04, 1.20390987e-05, 4.31506254e-04,
        5.78681011e-06, 3.82058133e-05, 9.88351894e-05, 2.41155317e-03,
        2.30698442e-05, 2.06000230e-04, 2.08412021e-04, 1.61556982e-05,
        2.42782480e-04, 4.58699325e-03, 1.71159772e-04, 8.93491844e-04,
        6.47941561e-05, 2.34036161e-05, 3.89947393e-03, 1.65094598e-03,
        7.27685750e-04, 1.67115635e-04, 5.35324398e-05, 6.18837366e-04,
        1.35280630e-02, 2.46602134e-03, 1.91286555e-03, 2.59830826e-03,
        5.01884380e-04, 1.02457672e-03, 2.04051903e-05, 4.27894149e-04,
        6.12251824e-07, 8.16191732e-06, 1.21410121e-03, 4.42045689e-07,
        8.24904084e-01, 1.19103004e-06, 4.65773046e-04, 1.170842

In [36]:
predict.shape

(1, 239)

In [37]:
pos = np.argmax(predict)
print(pos)

52


In [38]:
for word , index in tokenizer.word_index.items():
    if(index==pos):
        print(word)

kapadiya


In [39]:
test2 = "Developed and deployed live products utilizing"

In [40]:
token_text = tokenizer.texts_to_sequences([test2])[0]
#padding
padded_token_text = pad_sequences([token_text], maxlen=14, padding='pre')
#predict
print(padded_token_text)

[[ 0  0  0  0  0  0  0  0  9  1 58 59 60 61]]


In [41]:
predict = model.predict(padded_token_text)
predict

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step


array([[5.73326773e-08, 8.78658146e-04, 1.36972609e-04, 1.95722729e-02,
        5.13429331e-05, 1.55405432e-05, 9.76961965e-05, 2.08082306e-03,
        1.02932994e-04, 5.13554426e-08, 2.00730824e-06, 1.93919072e-06,
        5.41210684e-05, 3.31329502e-04, 4.90283037e-06, 5.95810940e-04,
        4.99790622e-05, 6.45624084e-07, 5.58067113e-04, 6.68326084e-06,
        9.37577784e-01, 4.23001969e-04, 2.63556576e-05, 8.72777528e-05,
        5.96171185e-06, 1.40790644e-05, 2.37815766e-05, 2.70414457e-04,
        1.46035643e-04, 7.98317797e-06, 3.01315436e-06, 2.19393405e-06,
        1.62877313e-05, 1.02720480e-06, 8.54486552e-06, 1.62149663e-05,
        5.42666430e-06, 9.38349240e-06, 2.39378210e-06, 1.96198948e-06,
        4.64162440e-07, 1.38916207e-07, 2.25653657e-05, 8.11560603e-05,
        5.51656740e-07, 2.71650624e-05, 2.74957740e-04, 1.12366171e-04,
        7.09984320e-08, 3.70483904e-05, 4.41800603e-06, 1.66357694e-07,
        7.62739660e-07, 1.91375378e-07, 5.56422674e-05, 1.820047

In [42]:
pos = np.argmax(predict)
print(pos)

20


In [43]:
for word , index in tokenizer.word_index.items():
    if(index==pos):
        print(word)

ocr


In [44]:
text = 'Thinkbiz'

In [45]:
for i in range(9):
    #tokenize
    token_text = tokenizer.texts_to_sequences([text])[0]
    #padding
    padded_token_text = pad_sequences([token_text], maxlen=14, padding='pre')
    #predict
    predict = model.predict(padded_token_text, verbose=0)
    pos = np.argmax(predict)

    for word , index in tokenizer.word_index.items():
        if(index==pos):
            text = text + " "+ word
            print(text)

Thinkbiz technology
Thinkbiz technology pvt
Thinkbiz technology pvt ltd
Thinkbiz technology pvt ltd junior
Thinkbiz technology pvt ltd junior python
Thinkbiz technology pvt ltd junior python developer
Thinkbiz technology pvt ltd junior python developer may
Thinkbiz technology pvt ltd junior python developer may 2024
Thinkbiz technology pvt ltd junior python developer may 2024 present


# Encoder-Decoder Model in NLP

In [46]:
from keras.models import Sequential, Model
from keras.layers import Input, Embedding, LSTM, Dense, SimpleRNN

In [47]:
max_length_input =10
max_length_output =15
input_vocab_size = 5
output_vocab_size = 10

In [48]:
# Define Encoder model
encoder_inputs = Input(shape=(max_length_input,))
encoder_embedding = Embedding(input_dim=input_vocab_size, output_dim=260)(encoder_inputs)
encoder_lstm = LSTM(156, return_state=True)
encoder_outputs, state_h, state_c = encoder_lstm(encoder_embedding)
encoder_states = [state_h, state_c]

In [49]:
# Define Decoder model
decoder_inputs = Input(shape=(max_length_output,))
decoder_embedding = Embedding(input_dim=output_vocab_size, output_dim=260)(decoder_inputs)
decoder_lstm = LSTM(156, return_sequences=True, return_state=True)
decoder_outputs, _, _ = decoder_lstm(decoder_embedding, initial_state=encoder_states)
decoder_dense = Dense(output_vocab_size, activation='softmax')
decoder_outputs = decoder_dense(decoder_outputs)

In [50]:
# Define the full Encoder-Decoder model
model = Model([encoder_inputs, decoder_inputs], decoder_outputs)

In [51]:
# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [52]:
# Print model summary
model.summary()

Model: "functional_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                  ┃ Output Shape              ┃         Param # ┃ Connected to               ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ input_layer_3 (InputLayer)    │ (None, 10)                │               0 │ -                          │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ input_layer_4 (InputLayer)    │ (None, 15)                │               0 │ -                          │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ embedding_1 (Embedding)       │ (None, 10, 260)           │           1,300 │ input_layer_3[0][0]        │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ embedding_2 (Embedding)       │ (None, 15, 260)           │           2,600 │ input_layer_4[0][0]        │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ lstm_1 (LSTM)                 │ [(None, 156), (None,      │         260,208 │ embedding_1[0][0]          │
│                               │ 156), (None, 156)]        │                 │                            │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ lstm_2 (LSTM)                 │ [(None, 15, 156), (None,  │         260,208 │ embedding_2[0][0],         │
│                               │ 156), (None, 156)]        │                 │ lstm_1[0][1], lstm_1[0][2] │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ dense_4 (Dense)               │ (None, 15, 10)            │           1,570 │ lstm_2[0][0]               │
└───────────────────────────────┴───────────────────────────┴─────────────────┴────────────────────────────┘

 Total params: 525,886 (2.01 MB)

 Trainable params: 525,886 (2.01 MB)

 Non-trainable params: 0 (0.00 B)

# Encoder-Decoder Model in Time-series Forecasting

In [53]:
from keras.layers import LSTM, Dense , Bidirectional, RepeatVector, TimeDistributed
from keras.models import Sequential
import keras
import numpy

In [54]:
time_window = 5
output = 2

In [55]:
model = Sequential()

# encoder
model.add(LSTM(100, activation='relu',input_shape=(time_window,1)))

# context vector
model.add(RepeatVector(output))

#decoder
model.add(LSTM(100, activation='relu', return_sequences=True))
model.add(TimeDistributed(Dense(1,activation='relu')))

model.compile(optimizer='adam', loss='mse')
model.summary()

C:\Users\Thinkbiz\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\rnn\rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ lstm_3 (LSTM)                        │ (None, 100)                 │          40,800 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ repeat_vector (RepeatVector)         │ (None, 2, 100)              │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_4 (LSTM)                        │ (None, 2, 100)              │          80,400 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ time_distributed (TimeDistributed)   │ (None, 2, 1)                │             101 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 121,301 (473.83 KB)

 Trainable params: 121,301 (473.83 KB)

 Non-trainable params: 0 (0.00 B)

In [56]:
test_model = keras.models.load_model('my_test_model.keras')

In [57]:
x_test = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
x_test = x_test.reshape((-1,5,1))
print(x_test.shape)

(4, 5, 1)


In [58]:
x_test

array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]],

       [[11],
        [12],
        [13],
        [14],
        [15]],

       [[16],
        [17],
        [18],
        [19],
        [20]]])

In [59]:
yhat = test_model.predict(x_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 495ms/step


In [60]:
yhat

array([[[ 5.7876782],
        [ 6.9925895]],

       [[11.046225 ],
        [12.039444 ]],

       [[15.970491 ],
        [17.075956 ]],

       [[21.03507  ],
        [22.078547 ]]], dtype=float32)

In [69]:
x_test = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
res = np.flip(ini_array)
# x_test = x_test.reshape((-1,5,1))
print(x_test.shape)

AttributeError: 'numpy.ndarray' object has no attribute 'reverse'

In [61]:
x_test = np.array([7203.5 , 7189.3 , 7152.55, 7105, 7048.35, 7020, 6995, 6947, 7063.55, 6900, 7063.55, 6900, 6863.6, 6778.35, 6735.85, 6710.55, 6600.1, 6585.75, 6600.8,6645.6])
x_test = x_test.reshape((-1,5,1))
print(x_test.shape)

# 7203.5, 7189.3 , 7152.55, 7105, 7048.35, 7020, 6995, 6947, 7063.55, 6900, 7063.55, 6900, 6863.6, 6778.35, 6735.85, 6710.55, 6600.1, 6585.75, 6600.8,6645.6

(4, 5, 1)


In [62]:
x_test

array([[[7203.5 ],
        [7189.3 ],
        [7152.55],
        [7105.  ],
        [7048.35]],

       [[7020.  ],
        [6995.  ],
        [6947.  ],
        [7063.55],
        [6900.  ]],

       [[7063.55],
        [6900.  ],
        [6863.6 ],
        [6778.35],
        [6735.85]],

       [[6710.55],
        [6600.1 ],
        [6585.75],
        [6600.8 ],
        [6645.6 ]]])

In [63]:
yhat = test_model.predict(x_test)
yhat

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 434ms/step


array([[[7132.5835],
        [7149.355 ]],

       [[6972.4077],
        [6987.385 ]],

       [[6866.002 ],
        [6882.3315]],

       [[6616.446 ],
        [6633.0015]]], dtype=float32)